### ISSUE TITLE
ambient_light is using native unit of measurement '#' which is not a valid unit for the device class ('illuminance') it is using

### ISSUE THREAD

**Issue by morikplay** [ApolloAutomation/MSR-1#26]
**Core** 2023.12.4
**Supervisor** 2023.12.0
**Operating System** 11.2
**Frontend** 20231208.2

Getting a HA startup warning  after installation of 1st MSR-1

```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:691
Integration: Sensor (documentation, issues)
First occurred: 11:09:24 PM (3 occurrences)
Last logged: 11:09:24 PM

    Entity sensor.sensor_presence_mbr_ltr390_ambient_light (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '#' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
    Entity sensor.sensor_presence_mbr_ltr390_uv_index (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'UVI' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
    Entity sensor.sensor_presence_mbr_ltr390_uv (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '#' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
```

relevant ESPHome config
```
substitutions:
  name: sensor-presence-mbr
  friendly_name: sensor-presence-mbr
packages:
  Apollo.Presence_Sensor: github://ApolloAutomation/MSR-1/Integrations/ESPHome/MSR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
```

**Comment by Nunjafush** [comment]
Same problem for me with HA warnings at startup. Been happening for multiple versions of Core, OS and ESPHome since installed in early January 2024:

Core 2024.2.2
Supervisor 2024.02.0
Operating System 12.0
Frontend 20240207.1
ESPHome 2024.2.0

Log Details:

> [Logger: homeassistant.components.sensor
> Source: components/sensor/__init__.py:738
> Integration: Sensor (documentation, issues)
> First occurred: 22:34:36 (3 occurrences)
> Last logged: 22:34:36
> 
> Entity sensor.apollo_msr_1_014790_ltr390_ambient_light (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '#' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
> Entity sensor.apollo_msr_1_014790_ltr390_uv_index (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'UVI' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
> Entity sensor.apollo_msr_1_014790_ltr390_uv (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '#' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22](div.snippet-clipboard-content:nth-child(3) > pre:nth-child(1))

Relevant ESPHome config:

> substitutions:
>   name: "apollo-msr1"
>   friendly_name: Apollo Multisensor Mk1 (MSR-1) 014790
> packages:
>   ApolloAutomation.MSR-1: github://ApolloAutomation/MSR-1/Integrations/ESPHome/MSR-1.yaml
> esphome:
>   name: ${name}
>   name_add_mac_suffix: false
>   friendly_name: ${friendly_name}

**Comment by kuzaxak** [comment]
I think it happens because wrong sensor got exported. I see in ESPHome UI 3, but in HA only 2 of them.
<img width="385" alt="image" src="https://github.com/ApolloAutomation/MSR-1/assets/5330267/949242af-9801-48e3-808a-ef039f0e94da">

**Comment by Nunjafush** [comment]
The settings for LTR390 are apparently not defined in the Apollo MSR1 configuration but just read from the LTR390 definition in ESPHome. 

In ESPHome, LTR390 had a device class of "illuminance" but yesterday's ESPHome 2024.3.0 update has now set it to "empty".
Since the update, I no longer get the errors in my log.

**Comment by axx4one** [comment]
> In ESPHome, LTR390 had a device class of "illuminance" but yesterday's ESPHome 2024.3.0 update has now set it to "empty". Since the update, I no longer get the errors in my log.

I can confirm that the Light lux sensor is now gone (not just disabled) after updating to ESPHome 2024.3.0. That‘s not a fix but rather a new issue. My automations using the MSR-1 lux light sensor aren’t working anymore. The ambient light sensor cannot be used as well (e.g. in the Sensor Light blueprint from @Blacky).

**Comment by neilmartin83** [comment]
Looks like we only have the `ambient_light` sensor for the LTR390 platform in https://github.com/ApolloAutomation/MSR-1/blob/789634b6d1ee802307523d167a15dbed01423654/Integrations/ESPHome/MSR-1.yaml#L460C1-L469C1

I'd suggest replacing the `ambient_light` sensor with just `light` as not sure if we need it:

> ambient_light (Optional): [Sensor](https://esphome.io/components/sensor/#config-sensor) counts for the Ambient light sensor (#). All options from Sensor.

```
    light:
      name: "LTR390 Light"
      id: ltr390light
```

If you add the below to your own configuration YAML in the ESPHome addon and reflash, it will expose the correct sensor (I also set the `update_interval` every 5 seconds as it's much more useful for my use case):

```
sensor:
  - platform: ltr390
    id: !extend ltr_390
    light:
      name: "LTR390 Light"
      id: ltr390light
    update_interval: 5s
```

**Comment by Bunton33** [comment]
We appreciate you sending us this update. I will talk with our technical
lead and see about implementing it. Please let us know if you need anything
else.

Best,
Justin Bunton
Apollo Automation

**Comment by TrevorSchirmer** [comment]
Apologies for the mistake. When we reduce the firmware size I removed it on accident when I meant to remove ambient_light.

The PR is merged and should let you update from the ESPHome add-on in about a day.

Also sorry for not seeing the new comments on this issue, I'll figure out how to get better notifications from these. Feel free to tag me in the future if we break something.

Thanks for your all's help!

Thanks,
Trevor

**Comment by cowboyrushforth** [comment]
Hey there, not sure if this is the best place to comment on this light sensor issue, but for me, I have two different MSR-1 units.

After this firmware update both show the light in HA - however, one unit is always "stuck" with whatever the light senses on bootup and never changes, the other one changes as the light level in the room changes.  For example if I shine a flashlight at it, it will correctly go way up to 120 lx, or if I turn off all the lights in the room it will go to 0 or 1 lx.

The other one works fine with regards to proximity and radar, but the light value again just stays at whatever it detects on bootup.  Is there a way to somehow hard reset that sensor?  I have tried reinstalling the firmware and power-cycling it but nothing seems to work.

Thanks!

**Comment by TrevorSchirmer** [comment]
> Hey there, not sure if this is the best place to comment on this light sensor issue, but for me, I have two different MSR-1 units.
> 
> After this firmware update both show the light in HA - however, one unit is always "stuck" with whatever the light senses on bootup and never changes, the other one changes as the light level in the room changes. For example if I shine a flashlight at it, it will correctly go way up to 120 lx, or if I turn off all the lights in the room it will go to 0 or 1 lx.
> 
> The other one works fine with regards to proximity and radar, but the light value again just stays at whatever it detects on bootup. Is there a way to somehow hard reset that sensor? I have tried reinstalling the firmware and power-cycling it but nothing seems to work.
> 
> Thanks!

Hello,

Yes that seems to be some problem. I'm worried about notifying everyone on this thread with some troubleshooting back and forth. Can we move this to a new issue on GitHub? Or feel free to jump into our support channel on Discord and we can walk you through some steps and try to get it resolved. We can try to change the update interval, and look at the sensor's built in portal to see if it is a HA/network problem or a hardware problem.

Discord: https://discord.gg/mMNgQPyF94 

Thanks!
-Trevor
