### ISSUE TITLE
MSR-1 crashes/hangs several times a day

### ISSUE THREAD

**Issue by allthesebugsv2** [ApolloAutomation/MSR-1#30]
Hey there,

the sensor is unfortunately hanging several times a day. This goes hand in hand with a sharp increase in the esp temperature:

![Screenshot 2024-01-28 194003](https://github.com/ApolloAutomation/MSR-1/assets/50304079/41af23cf-fbb2-4850-922b-1e8fb3d10b1c)

Usually, it restarts then at some point after becoming unavailable. But sometimes I even have to re-plug its power to make it available again. I have not noticed a pattern regarding this.

Firmware: 2023.11.6 (Dec 8 2023, 16:57:05)
Hardware: 23.12081

If there is a firmware update available, then I don't see where. I do not use ESPHome (only Home Assistant inside Docker), so I cannot follow this guide: https://wiki.apolloautomation.cloud/books/general/page/updating-firmware

**Comment by Bunton33** [comment]
Hello,

Sorry to hear about the esp shutting down. There is a newer firmware
version. Can you try following this wiki guide?
https://wiki.apolloautomation.cloud/books/msr-1/page/manually-uploading-code-through-esphome


It uses ESPHome web so you shouldn't need the addon. Let us know how it
goes.

Thanks,
Justin Bunton
Apollo Automation

**Comment by allthesebugsv2** [comment]
Thanks, I have managed to update the firmware and am now running
Firmware: 2023.11.6 (Jan 10 2024, 23:20:18)
Hardware: 24.1.10.1

However, even after updating I have had 3 crashes in the last 24h:
![Screenshot 2024-01-30 134617](https://github.com/ApolloAutomation/MSR-1/assets/50304079/a2b5c650-ee57-4a0f-a48f-db16e056d1f3)

**Comment by Bunton33** [comment]
Hello,

Glad to hear that you were able to update the firmware. We are not exactly
sure what's causing the device to crash though, so we will exchange it for
a new one. What is your order number?

Best,
Justin
Apollo Automation

**Comment by allthesebugsv2** [comment]
That is extremely kind, I'll got back to you via mail
